[package]
name = "the-book"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ctrlc = "3.4.4"
human-panic = "2.0.0"
mime = "0.3.17"
pdf-extract = "0.7.7"
tokio = { version = "1.37.0", features = ["full"] }
